# Generated by Django 3.2 on 2021-06-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='topic',
            new_name='topics',
        ),
    ]
