# Generated by Django 3.2 on 2021-06-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='subscription',
            new_name='subscriptions',
        ),
    ]
